#!/usr/bin/env bash

install() {
  link "$REPOSITORY_ROOT/.vimrc" ~/.vimrc
  link "$REPOSITORY_ROOT" ~/.vim
  mkdir -p "$REPOSITORY_ROOT/swp"
  setup_submodules
}

source <(curl -Lfs https://git.io/lnkr)
